### ISSUE TITLE
Roadmap to complete the base system

### ISSUE THREAD

**Issue by TheColdPot** [TheColdPot/potty-survival-3#1]
- [ ] A complete revamp for magic system.
- [ ] Faction and class system.
- [ ] Introduce a leveling system that grants permanent buff.
- [x] Redesign how rarity (common, rare, epic) and weapon type (katana, sword, dagger) look in lore.
- [x] Add `#` to score holders for most virtual entites.
- [ ] Move most of `potty` things into independent namespaces
- [x] Revamp how mob selector in combat system works.
- [ ] Enhance the optimization system.
- [x] Gear enchantment/scroll system.

**Comment by TheColdPot** [comment]
Commit bcc366f should have made the migration work almost done. After the dungeon and the magic system is fully functional, the migration will take place then.

**Comment by TheColdPot** [comment]
*Design note*

Right now 

$$\text{Attack Cooldown} \propto 1/\text{Attack Speed}$$

instead of 

$$\text{Attack Cooldown} \propto \text{Attack Speed}$$

This may seem weird.
